[build]
builder = "nixpacks"

[deploy]
startCommand = "hypercorn app.main:app --bind \"[::]:$PORT\""
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
PYTHON_VERSION = "3.11"
